### ISSUE TITLE
Peer to peer code review.

### ISSUE THREAD

**Issue by Nowembabazi** [ManarOmari/Project-1-Setup-and-mobile-version-skeleton#12]
#In this peer to peer code review, we achieved the following..
- Edit your html the toggle bar is still showing on your desktop version.
- Try and retain the past working branches for future peer to peer code reviews.
- Edit the padding on mobile version and the desktop version.
On the other hand. I noticed great organisation and good display of your html syntax.

**Comment by ManarOmari** [comment]
Thanks @Nowembabazi  
I am going to update and fix the issues
